services:
  - type: web
    name: bizz-bazzar
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1